// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 /** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  chaptersSidebar: [
    // Part I: Foundations
    {
      type: 'category',
      label: 'Part I - Foundations of Physical AI',
      items: [{type: 'autogenerated', dirName: 'part-i'}],
    },
    // Part II: ROS 2
    {
      type: 'category',
      label: 'Part II - ROS 2 Architecture',
      items: [{type: 'autogenerated', dirName: 'part-ii'}],
    },
    // Part III: Simulation
    {
      type: 'category',
      label: 'Part III - Simulation & Digital Twins',
      items: [{type: 'autogenerated', dirName: 'part-iii'}],
    },
    // Part IV: Perception
    {
      type: 'category',
      label: 'Part IV - Perception & Navigation',
      items: [{type: 'autogenerated', dirName: 'part-iv'}],
    },
    // Part V: Cognition
    {
      type: 'category',
      label: 'Part V - Cognition & Action',
      items: [{type: 'autogenerated', dirName: 'part-v'}],
    },
  ],
};

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */

export default sidebars;
